name: Github Actions Example
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Push Trigger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
            - name: Install dependencies
              run: npm install
            - name: Hello world action step
              id: hello
              with:
                  who-to-greet: "Ivan"
            - name: time of action
              run: echo "The time was ${{ steps.hello.outputs.time }}"
            - name: Test project
              run: npm test
