name: Github Actions Example
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        name: Pull request Trigger
        runs-on: ubuntu-latest
        steps:
            - name: who issue the pull request
              run: echo "Pull request by other user"
            - name: first interaction
              uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
                  pr-message: "Message that will be displayed on users' first pr. Look, a `code block` for markdown."
